### ISSUE TITLE
chapter 3 comments

### ISSUE THREAD

**Issue by KewTeacher** [ShellHe/Chapter2--4#2]
Hi Shell,
In general, good work!
Please place your files for chapter 3 in the chapter 3 folder. 

For exercise 5, the text says to save separate files as 5a, 5b, 5c etc.. However, It looks like you must have done them all. Next time save them as per the instructions.

Same comments for 6. I wanted each one separately, but you made a program that allows the user to pick how many side, which accomplishes the same thing. So just remember next time, follow the instructions closely.

11- your star is almost there but not quite right. Your turn angle is 140, but if you go through the exercise turning your phone, you'll see that your phone makes two full rotations. The angle would be 360*2/5 or 144. Please revise your code by changing 140 to  360*2/5.

12 - You still need to do this OR you can make a creative turtle loop program.

**Comment by ShellHe** [comment]
Hi, Mr Aronson!
I just fixed all my error!

**Comment by KewTeacher** [comment]
Please place all your files for chapter 3 in the chapter 3 folder. Right now you only have three files in there.
